from collections.abc import Awaitable, Callable
from typing import Protocol

from EvernightAI.core.schema.skill import (
    RenderedSkill,
    SkillRenderRequest,
    SkillCapability,
    SkillDefinition,
    SkillTemplateConfig,
    SkillTemplateUpdate,
)


SkillRendererProtocol = Callable[[SkillRenderRequest], Awaitable[RenderedSkill]]
SkillTemplateFactoryProtocol = Callable[[SkillTemplateConfig], SkillRendererProtocol]


class SkillTemplateStoreProtocol(Protocol):
    def save(self, config: SkillTemplateConfig) -> None: ...
    def list_configs(self) -> list[SkillTemplateConfig]: ...
    def delete(self, skill_name: str) -> None: ...
    def close(self) -> None: ...
    def is_ready(self) -> bool: ...


class SkillManageProtocol(Protocol):
    """
    技能管理协议
    """

    def list_skills(self) -> list[SkillDefinition]: ...

    def get_skill(self, skill_name: str) -> SkillDefinition: ...

    def supports(self, skill_name: str, capability: SkillCapability) -> bool: ...

    def validate_input(self, request: SkillRenderRequest) -> None: ...

    def create_template(self, config: SkillTemplateConfig) -> SkillDefinition: ...
    def get_template(self, skill_name: str) -> SkillTemplateConfig: ...
    def update_template(self, skill_name: str, update: SkillTemplateUpdate) -> SkillDefinition: ...
    def delete_template(self, skill_name: str) -> None: ...
    def restore(self) -> None: ...

    async def render(self, request: SkillRenderRequest) -> RenderedSkill: ...


class SkillRegisterProtocol(Protocol):
    """
    技能注册协议
    """

    def register(
        self,
        skill: SkillDefinition,
        renderer: SkillRendererProtocol,
    ) -> None: ...

    def unregister(self, skill_name: str) -> None: ...

    def get(self, skill_name: str) -> SkillDefinition: ...

    def get_renderer(self, skill_name: str) -> SkillRendererProtocol: ...

    def has(self, skill_name: str) -> bool: ...

    def list_skills(self) -> list[SkillDefinition]: ...
